"""empty message

Revision ID: 440180672239
Revises: 006e379c60a6
Create Date: 2022-04-08 20:45:36.008682

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '440180672239'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulegroup',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('question',
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('rule_id', sa.Integer(), nullable=True),
                    sa.Column('question', sa.String(), nullable=True),
                    sa.Column('answer_index', sa.Integer(), nullable=True),
                    sa.Column('answer_text', sa.String(), nullable=True),
                    sa.Column('created', sa.Date(), nullable=True),
                    sa.Column('last_edited', sa.Date(), nullable=True),
                    sa.Column('signature', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['rulegroup.id'], ),
                    sa.PrimaryKeyConstraint('signature')
                    )
    op.create_table('multiplechoice',
                    sa.Column('rule_signature', sa.String(), nullable=False),
                    sa.Column('index', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['rule_signature'], ['question.signature'], ),
                    sa.PrimaryKeyConstraint('rule_signature', 'index')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplechoice')
    op.drop_table('question')
    op.drop_table('rulegroup')
    # ### end Alembic commands ###
