"""empty message

Revision ID: 6ea786c6938c
Revises: be003b0637e8
Create Date: 2022-04-24 18:31:40.759949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea786c6938c'
down_revision = 'be003b0637e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regeltest_icon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('icon', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon')
    )
    op.create_table('regeltest_design',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icon_position_id', sa.Integer(), nullable=True),
    sa.Column('title_position_id', sa.Integer(), nullable=True),
    sa.Column('title_fontsize', sa.Integer(), nullable=True),
    sa.Column('description_position_id', sa.Integer(), nullable=True),
    sa.Column('description_fontsize', sa.Integer(), nullable=True),
    sa.Column('namefield_position_id', sa.Integer(), nullable=True),
    sa.Column('namefield_fontsize', sa.Integer(), nullable=True),
    sa.Column('question_fontsize', sa.Integer(), nullable=True),
    sa.Column('question_points_fontsize', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['description_position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['icon_position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['namefield_position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['title_position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regeltest_question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('regeltest_id', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('available_points', sa.Integer(), nullable=True),
    sa.Column('is_multiple_choice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.signature'], ),
    sa.ForeignKeyConstraint(['regeltest_id'], ['regeltest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('regeltest_question_assoc')
    op.add_column('regeltest', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('regeltest', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.add_column('regeltest', sa.Column('design_id', sa.Integer(), nullable=True))
    with op.batch_alter_table("regeltest") as batch_op:
        batch_op.create_foreign_key('regeltest_design', 'regeltest_design', ['design_id'], ['id'])
        batch_op.create_foreign_key('regeltest_icon', 'regeltest_icon', ['icon_id'], ['id'])
    op.drop_column('regeltest', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regeltest', sa.Column('icon', sa.BLOB(), nullable=True))
    op.drop_constraint('regeltest_design', 'regeltest', type_='foreignkey')
    op.drop_constraint('regeltest_icon', 'regeltest', type_='foreignkey')
    op.drop_column('regeltest', 'design_id')
    op.drop_column('regeltest', 'icon_id')
    op.drop_column('regeltest', 'uuid')
    op.create_table('regeltest_question_assoc',
    sa.Column('question_signature', sa.VARCHAR(), nullable=False),
    sa.Column('regeltest_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_signature'], ['question.signature'], ),
    sa.ForeignKeyConstraint(['regeltest_id'], ['regeltest.id'], ),
    sa.PrimaryKeyConstraint('question_signature', 'regeltest_id')
    )
    op.drop_table('regeltest_question')
    op.drop_table('regeltest_design')
    op.drop_table('regeltest_icon')
    op.drop_table('position')
    # ### end Alembic commands ###
