"""empty message

Revision ID: b8c3becc2f97
Revises: 440180672239
Create Date: 2022-04-08 23:24:29.299625

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b8c3becc2f97'
down_revision = '440180672239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regeltest',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association',
                    sa.Column('question_signature', sa.String(), nullable=False),
                    sa.Column('regeltest_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['question_signature'], ['question.signature'], ),
                    sa.ForeignKeyConstraint(['regeltest_id'], ['regeltest.id'], ),
                    sa.PrimaryKeyConstraint('question_signature', 'regeltest_id')
                    )
    op.create_table('statistics',
                    sa.Column('question_signature', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['question_signature'], ['question.signature'], ),
                    sa.PrimaryKeyConstraint('question_signature')
                    )
    op.alter_column(table_name='question', new_column_name='question_id', column_name='rule_id')
    op.alter_column(table_name='multiplechoice', new_column_name='question_signature', column_name='rule_signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='question', column_name='question_id', new_column_name='rule_id')
    op.alter_column(table_name='multiplechoice', column_name='question_signature', new_column_name='rule_signature')
    op.drop_table('statistics')
    op.drop_table('association')
    op.drop_table('regeltest')
    # ### end Alembic commands ###
