"""empty message

Revision ID: be003b0637e8
Revises: 440180672239
Create Date: 2022-04-16 21:00:32.421746

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'be003b0637e8'
down_revision = '440180672239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regeltest',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('icon', sa.BLOB(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('regeltest_question_assoc',
                    sa.Column('question_signature', sa.String(), nullable=False),
                    sa.Column('regeltest_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['question_signature'], ['question.signature'], ),
                    sa.ForeignKeyConstraint(['regeltest_id'], ['regeltest.id'], ),
                    sa.PrimaryKeyConstraint('question_signature', 'regeltest_id')
                    )
    op.create_table('statistics',
                    sa.Column('question_signature', sa.String(), nullable=False),
                    sa.Column('continous_solved_count', sa.Integer(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('correct_solved', sa.Integer(), nullable=True),
                    sa.Column('wrong_solved', sa.Integer(), nullable=True),
                    sa.Column('last_tested', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['question_signature'], ['question.signature'], ),
                    sa.PrimaryKeyConstraint('question_signature')
                    )
    op.rename_table('rulegroup', 'question_group')
    op.rename_table('multiplechoice', 'multiple_choice')

    op.alter_column(table_name='question', column_name='rule_id', new_column_name='question_id')
    op.alter_column(table_name='multiple_choice', column_name='rule_signature', new_column_name='question_signature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='question', column_name='question_id', new_column_name='rule_id')
    op.alter_column(table_name='multiple_choice', column_name='question_signature', new_column_name='rule_signature')

    op.rename_table('question_group', 'rulegroup')
    op.rename_table('multiple_choice', 'multiplechoice')

    op.drop_table('statistics')
    op.drop_table('regeltest_question_assoc')
    op.drop_table('regeltest')
    # ### end Alembic commands ###
